services:
  backend:
    image: appqueue-backend
    build:
      context: ./v1/backend
      dockerfile: Dockerfile.dev
    container_name: appqueue-backend
    ports:
      - "8000:8000"
    volumes:
      - ./v1/backend:/app
    environment:
      - TZ=America/Lima
    restart: unless-stopped

  frontend:
    image: appqueue-frontend
    build:
      context: ./v1/frontend
      dockerfile: Dockerfile.dev
    container_name: appqueue-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./v1/frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=America/Lima
    depends_on:
      - backend
